modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/YourRepo/Issues"

[[mods]]
modId="cclogistics"
version="${file.jarVersion}"
displayName="Create Colony Logistics"
displayURL="https://yourwebsite.com"
logoFile="logo.png"
authors="OGTenzoHD"
description='''
Logistics Addon for MineColonies and Create.
'''

[[mixins]]
config="cclogistics.mixins.json"

[[dependencies.cclogistics]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cclogistics]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cclogistics]]
    modId="minecolonies"
    type="required"
    versionRange="[1.0,)"
    ordering="NONE"   # FIX: Change AFTER to NONE to prevent advancement crash
    side="BOTH"

[[dependencies.cclogistics]]
    modId="create"
    type="required"
    versionRange="[0.5.1,)"
    ordering="NONE"   # FIX: Change AFTER to NONE to prevent advancement crash
    side="BOTH"